// GENERATED by build.mjs — do not edit. The plugin's baked origin:
// derived from the MCP server url so hook transport and connector always share a stack.
export const BAKED_ORIGIN = 'https://pathsayer.com';
